#!/bin/bash
# Template: RDC Setup — 生成 RDC 约束文件
# 由 chip-spyglass-rdc-chk 生成
# 用法: bash template_rdc_setup.sh <module> <cdc_sgdc_file>

MODULE=$1
CDC_SGDC="${2:-ds/run/${MODULE}.sgdc}"
RDC_FILE="ds/run/${MODULE}.rdc.tcl"

mkdir -p ds/run

cat > "$RDC_FILE" << RDC_EOF
# ============================================================
# RDC Constraints for ${MODULE}
# Auto-generated by chip-spyglass-rdc-chk
# Date: $(date +%Y-%m-%d)
# ============================================================

# --- 复用 CDC 约束（时钟/复位/常量/准静态） ---
# 如果 CDC 约束存在，source 进来避免重复定义
# source ${CDC_SGDC}

# --- Top Module ---
current_design ${MODULE}

# --- RDC 复位定义 ---
# 格式: create_reset -name <name> -active <low|high> -async|-sync
# 请按实际设计修改以下复位定义
# create_reset -name "rst_n" -active_low -async
# create_reset -name "rst_sw" -active_high -sync
# create_reset -name "rst_dbg" -active_high -sync

# --- 复位释放顺序（最重要） ---
# 格式: set_rdc_define_assertion_sequence -from_reset <src> -to_reset <dst>
# to_reset 的复位先于 from_reset 释放 → RDC 安全
# set_rdc_define_assertion_sequence \
#     -from_reset {rst_sw} \
#     -to_reset {rst_n}

# --- 复位分组 ---
# 同组复位之间的 RDC 自动安全
# set_reset_groups -name grp_por -group {rst_n}
# set_reset_groups -name grp_func -group {rst_sw rst_dbg}

# --- RDC Qualifier（阻断信号） ---
# 阻断 RDC 路径的信号（如门控使能、隔离信号）
# rdc_qualifier -signal "cfg_rdc_gate" -value 1

# --- Scenario-Based RDC（降噪） ---
# 区分 Power-On Reset 和 Functional Reset 场景
# configure_rdc_scenario -name "por_mode" \
#     -active_resets {rst_n} \
#     -inactive_resets {rst_sw rst_dbg}
# configure_rdc_scenario -name "func_mode" \
#     -active_resets {rst_sw rst_dbg} \
#     -inactive_resets {rst_n}

# --- Reset-less Flop 处理 ---
# 跳过无复位的流水线级，聚焦数据损坏端点
# configure_rdc_corrupt -skip_resetless_flops true

# --- Ignore Paths ---
# 非功能路径（如 DFT 专用信号）
# rdc_false_path -from src_flop -to dst_flop

RDC_EOF

echo "[RDC-SETUP] Generated $RDC_FILE"
echo "[RDC-SETUP] 请按实际设计修改复位定义、复位释放顺序和复位分组"
echo "[RDC-SETUP] 复位释放顺序（set_rdc_define_assertion_sequence）是降噪的核心"
