#!/bin/bash
# Template: CDC Setup — 生成 SGDC 约束文件
# 由 chip-spyglass-cdc-chk 生成
# 用法: bash template_cdc_setup.sh <module> <clock_info> <reset_info>

MODULE=$1
CLOCK_INFO="${2:-}"
RESET_INFO="${3:-}"
SGDC_FILE="ds/run/${MODULE}.sgdc"

mkdir -p ds/run

cat > "$SGDC_FILE" << SGDC_EOF
# ============================================================
# SGDC Constraints for ${MODULE}
# Auto-generated by chip-spyglass-cdc-chk
# Date: $(date +%Y-%m-%d)
# ============================================================

# --- Top Module ---
current_design ${MODULE}

# --- Clock Definitions ---
# 格式: clock -name <name> -period <ns> -edge <rise> <fall>
# 请按实际设计修改以下时钟定义
${CLOCK_INFO:-# clock -name "clk_main" -period 10 -edge 0 5
# clock -name "clk_bus"  -period 20 -edge 0 10}

# --- Reset Definitions ---
# 格式: reset -name <name> -value <0|1>
${RESET_INFO:-# reset -name "rst_n" -value 0}

# --- Black Box Modules ---
# PLL 等时钟生成模块应设为 Black Box
# set_option stop <pll_module_name>
# abstract_port -module pll_top -ports clk_out -clock clk_main

# --- MUX Clock Selection ---
# 时钟 MUX 的选择端应设为 set_case_analysis
# set_case_analysis -value 0 [get_ports test_mode]

# --- Quasi-Static Signals ---
# 配置寄存器等准静态信号
# quasi_static -name "cfg_*"

# --- CDC False Paths ---
# 非功能路径（如 DFT 专用信号）
# cdc_false_path -from src_flop -to dst_flop

# --- Abstract Port Constraints ---
# Black Box 端口时钟域约束
# abstract_port -module <mod> -ports <port> -clock <clk>
# signal_in_domain -domain <clk> -signals <signal>

SGDC_EOF

echo "[CDC-SETUP] Generated $SGDC_FILE"
echo "[CDC-SETUP] 请按实际设计修改时钟、复位和 Black Box 定义"
